public enum AudioFieldEnum 
{
	CLICK_BUTTON = 0,
	AMBIANT_GAME = 1,
	SETUP_DAM = 2,
	WATER_GLIDING = 3,
	VICTORY_JINGLE = 4,
	DEFEAT_JINGLE = 5,
	BREAK_TRAP = 6,
	DROWNED_OBJECT = 7,
	INVALID_DAM = 8,

}
